#!/usr/bin/env python3
"""Regenerate the "Open and recently shipped items" section of each plugin's
FIELD-QUESTIONS.md from docs/inbox/dispositions.json.

Usage: render_field_questions.py [--check] [--keep-versions N]

Maintainer tool — lives in this repo, is not shipped in any plugin. The
section it writes is what closes the loop for a field reporter: the agent
that filed `qa-0.12.0-20260909-weatherapp-2` sees that it landed, and the
next report says "seen again" by id instead of re-describing.

Rules:
- Everything NOT shipped is always listed (new, declined, settled, backlog,
  deferred): those are the items a reporter is most likely to re-raise.
- Shipped items are listed for the N most recent shipping versions of the
  plugin (default 2), so the section stays a page as releases accumulate.
- `no-action` items are never listed.
- The output is deterministic (no dates): re-running with unchanged
  dispositions changes nothing.

--check exits 1 if any FIELD-QUESTIONS.md is out of date (nothing written) —
for the pre-commit validation sweep.
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEGIN = "<!-- BEGIN generated by tools/render_field_questions.py — do not edit -->"
END = "<!-- END generated -->"
ORDER = ("new", "backlog", "deferred", "declined", "settled", "shipped")
HEAD = {"new": "Reported, not yet decided",
        "backlog": "In the backlog (accepted, not built)",
        "deferred": "Deferred",
        "declined": "Declined",
        "settled": "Declined as already settled",
        "shipped": "Shipped"}

def vkey(v):
    return tuple(int(x) if x.isdigit() else 0 for x in re.split(r"[.-]", v or "0"))

def idkey(i):
    m = re.match(r"(.*)-(\d+)$", i["id"])
    return (m.group(1), int(m.group(2))) if m else (i["id"], 0)

def render(items, keep_versions):
    items = [i for i in items if i.get("status") in ORDER]
    versions = sorted({i.get("version") for i in items
                       if i.get("status") == "shipped" and i.get("version")},
                      key=vkey, reverse=True)[:keep_versions]
    L = []
    shown = 0
    for status in ORDER:
        group = [i for i in items if i.get("status") == status
                 and (status != "shipped" or i.get("version") in versions)]
        if not group:
            continue
        L.append(f"**{HEAD[status]}**")
        L.append("")
        if status == "shipped":
            group.sort(key=lambda i: (tuple(-x for x in vkey(i.get("version"))), idkey(i)))
        else:
            group.sort(key=idkey)
        for i in group:
            line = f"- `{i['id']}` — "
            if status == "shipped":
                line += f"shipped in {i.get('version')} — "
            line += i.get("title", "").strip()
            if i.get("reason"):
                line += f" _({i['reason'].strip().rstrip('.')}.)_"
            L.append(line)
            shown += 1
        L.append("")
    if not L:
        return "_No field items recorded for this plugin yet._"
    older = sum(1 for i in items if i.get("status") == "shipped"
                and i.get("version") not in versions)
    if older:
        L.append(f"_{older} item(s) shipped in earlier versions are not listed._")
        L.append("")
    return "\n".join(L).rstrip()

def main():
    check = "--check" in sys.argv
    keep = 2
    if "--keep-versions" in sys.argv:
        keep = int(sys.argv[sys.argv.index("--keep-versions") + 1])
    dpath = os.path.join(ROOT, "docs", "inbox", "dispositions.json")
    with open(dpath, encoding="utf-8") as fh:
        disp = json.load(fh)
    by_plugin = {}
    for i in disp.get("items", []):
        by_plugin.setdefault(i.get("plugin"), []).append(i)
    stale, written = [], []
    for name in sorted(os.listdir(ROOT)):
        fq = os.path.join(ROOT, name, "FIELD-QUESTIONS.md")
        if not os.path.exists(fq):
            continue
        with open(fq, encoding="utf-8") as fh:
            text = fh.read()
        if BEGIN not in text or END not in text:
            print(f"render_field_questions: {name}/FIELD-QUESTIONS.md has no generated "
                  f"block markers", file=sys.stderr)
            sys.exit(1)
        head, rest = text.split(BEGIN, 1)
        _old, tail = rest.split(END, 1)
        new = head + BEGIN + "\n" + render(by_plugin.get(name, []), keep) + "\n" + END + tail
        if new != text:
            stale.append(name)
            if not check:
                with open(fq, "w", encoding="utf-8") as fh:
                    fh.write(new)
                written.append(name)
    if check and stale:
        print("render_field_questions: out of date: " + ", ".join(stale)
              + " — run tools/render_field_questions.py", file=sys.stderr)
        sys.exit(1)
    print(json.dumps({"written": written, "up_to_date": not stale}))

if __name__ == "__main__":
    main()
